import SwiftUI

struct OnboardingView: View {
    @AppStorage("hasCompletedOnboarding") private var hasCompletedOnboarding = false
    @AppStorage("notifications_enabled") private var notificationsEnabled = true
    @State private var currentPage = 0
    @State private var notificationGranted = false

    private let totalPages = 4

    var body: some View {
        VStack(spacing: 0) {
            TabView(selection: $currentPage) {
                OnboardingPageView(
                    systemImage: "newspaper.fill",
                    title: "Welcome to Velari",
                    description: "Your weekly AI news digest, curated by AI. Stay on top of the most important developments in artificial intelligence."
                )
                .tag(0)

                OnboardingPageView(
                    systemImage: "sparkles",
                    title: "Stay Informed",
                    description: "Weekly digests with the top AI stories, searchable archive, offline reading, and personal bookmarks — all in one place."
                )
                .tag(1)

                OnboardingPageView(
                    systemImage: "checkmark.shield.fill",
                    title: "AI-Curated, Human-Verified",
                    description: "Every digest is generated by AI from hundreds of sources. We always link to the originals so you can verify the facts."
                )
                .tag(2)

                notificationPage
                    .tag(3)
            }
            .tabViewStyle(.page(indexDisplayMode: .never))
            .animation(.easeInOut, value: currentPage)

            bottomControls
                .padding(.horizontal, 24)
                .padding(.bottom, 16)
        }
    }

    private var notificationPage: some View {
        VStack(spacing: 24) {
            Spacer()

            Image(systemName: "bell.badge.fill")
                .font(.system(size: 80))
                .foregroundStyle(VelariColors.primary)
                .symbolRenderingMode(.hierarchical)

            VStack(spacing: 12) {
                Text("Never Miss a Digest")
                    .font(.title)
                    .fontWeight(.bold)
                    .multilineTextAlignment(.center)

                Text("Get notified every Sunday when a new AI news digest is published.")
                    .font(.body)
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 32)
            }

            Button {
                requestNotifications()
            } label: {
                Label("Enable Notifications", systemImage: "bell.fill")
                    .font(.headline)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 14)
            }
            .buttonStyle(.borderedProminent)
            .tint(VelariColors.primary)
            .padding(.horizontal, 40)
            .padding(.top, 8)

            if notificationGranted {
                Label("Notifications enabled", systemImage: "checkmark.circle.fill")
                    .foregroundStyle(.green)
                    .font(.subheadline)
                    .transition(.scale.combined(with: .opacity))
            }

            Spacer()
            Spacer()
        }
        .padding()
    }

    private var bottomControls: some View {
        VStack(spacing: 16) {
            // Page indicator
            HStack(spacing: 8) {
                ForEach(0..<totalPages, id: \.self) { index in
                    Circle()
                        .fill(index == currentPage ? VelariColors.primary : Color.gray.opacity(0.3))
                        .frame(width: 8, height: 8)
                        .scaleEffect(index == currentPage ? 1.2 : 1.0)
                        .animation(.spring(duration: 0.3), value: currentPage)
                }
            }

            if currentPage == totalPages - 1 {
                Button {
                    hasCompletedOnboarding = true
                } label: {
                    Text("Get Started")
                        .font(.headline)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 14)
                }
                .buttonStyle(.borderedProminent)
                .tint(VelariColors.primary)
                .transition(.scale.combined(with: .opacity))
            } else {
                HStack {
                    Button("Skip") {
                        hasCompletedOnboarding = true
                    }
                    .foregroundStyle(.secondary)

                    Spacer()

                    Button {
                        withAnimation {
                            currentPage += 1
                        }
                    } label: {
                        HStack(spacing: 4) {
                            Text("Next")
                            Image(systemName: "arrow.right")
                        }
                        .fontWeight(.semibold)
                    }
                    .foregroundStyle(VelariColors.primary)
                }
            }
        }
    }

    private func requestNotifications() {
        Task {
            let granted = await NotificationService.requestPermission()
            withAnimation {
                notificationGranted = granted
                notificationsEnabled = granted
            }
        }
    }
}
