import SwiftUI

struct StoryDetailView: View {
    let story: Story
    let issueDate: String
    let modelUsed: String
    let cache: CacheService

    @State private var safariURL: IdentifiableURL?
    @State private var isBookmarked: Bool = false

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                // Header
                HStack(spacing: 8) {
                    ImportanceBadge(importance: story.importance)
                    CategoryPill(category: story.category)
                    Spacer()
                }

                // Title
                Text(story.title)
                    .font(.title2)
                    .fontWeight(.bold)

                // Date
                Text(DateFormatting.displayDate(story.datePublished))
                    .font(.subheadline)
                    .foregroundStyle(.secondary)

                Divider()

                // Full summary
                Text(story.cleanSummary)
                    .font(.body)
                    .lineSpacing(4)

                // Sources
                if !story.sources.isEmpty {
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Sources")
                            .font(.headline)
                            .padding(.top, 8)

                        ForEach(story.sources, id: \.url) { source in
                            sourceCard(source)
                        }
                    }
                }

                // Tags
                if !story.tags.isEmpty {
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Tags")
                            .font(.headline)
                            .padding(.top, 8)

                        FlowLayout(spacing: 6) {
                            ForEach(story.tags, id: \.self) { tag in
                                TagChip(tag: tag)
                            }
                        }
                    }
                }

                // AI Disclaimer
                Divider()
                    .padding(.top, 8)

                Text("This summary was generated by AI (\(modelUsed)). Always verify claims with original sources.")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
                    .padding(.bottom, 32)
            }
            .padding()
        }
        .navigationTitle("Story")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItemGroup(placement: .topBarTrailing) {
                ShareLink(
                    item: shareText,
                    subject: Text(story.title),
                    message: Text(story.cleanSummary)
                ) {
                    Image(systemName: "square.and.arrow.up")
                }

                Button {
                    HapticService.bookmarkToggle()
                    cache.toggleBookmark(story: story, issueDate: issueDate)
                    isBookmarked.toggle()
                } label: {
                    Image(systemName: isBookmarked ? "bookmark.fill" : "bookmark")
                        .foregroundStyle(isBookmarked ? VelariColors.primary : .primary)
                }
            }
        }
        .sheet(item: $safariURL) { item in
            SafariView(url: item.url)
                .ignoresSafeArea()
        }
        .onAppear {
            isBookmarked = cache.isBookmarked(storyId: story.id)
            cache.markAsRead(storyId: story.id, issueDate: issueDate)
        }
    }

    private func sourceCard(_ source: Source) -> some View {
        Button {
            if let url = URL(string: source.url) {
                safariURL = IdentifiableURL(url: url)
            }
        } label: {
            VStack(alignment: .leading, spacing: 4) {
                Text(source.publisher)
                    .font(.subheadline)
                    .fontWeight(.semibold)
                Text(source.title)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(2)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(12)
            .background(Color(.tertiarySystemBackground))
            .clipShape(RoundedRectangle(cornerRadius: 8))
        }
        .buttonStyle(.plain)
    }

    private var shareText: String {
        let url = story.sources.first?.url ?? ""
        return "\(story.title)\n\nRead more: \(url)\n\nShared via Velari - AI News Digest"
    }
}

// MARK: - Identifiable URL wrapper for sheet

struct IdentifiableURL: Identifiable {
    let url: URL
    var id: String { url.absoluteString }
}

// MARK: - Flow Layout for tags

struct FlowLayout: Layout {
    var spacing: CGFloat = 8

    func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) -> CGSize {
        let result = layout(subviews: subviews, proposal: proposal)
        return result.size
    }

    func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) {
        let result = layout(subviews: subviews, proposal: proposal)
        for (index, position) in result.positions.enumerated() {
            subviews[index].place(at: CGPoint(x: bounds.minX + position.x, y: bounds.minY + position.y), proposal: .unspecified)
        }
    }

    private func layout(subviews: Subviews, proposal: ProposedViewSize) -> (positions: [CGPoint], size: CGSize) {
        let maxWidth = proposal.width ?? .infinity
        var positions: [CGPoint] = []
        var x: CGFloat = 0
        var y: CGFloat = 0
        var rowHeight: CGFloat = 0

        for subview in subviews {
            let size = subview.sizeThatFits(.unspecified)
            if x + size.width > maxWidth && x > 0 {
                x = 0
                y += rowHeight + spacing
                rowHeight = 0
            }
            positions.append(CGPoint(x: x, y: y))
            rowHeight = max(rowHeight, size.height)
            x += size.width + spacing
        }

        return (positions, CGSize(width: maxWidth, height: y + rowHeight))
    }
}
